const beforeusPics = [
    "https://drive.google.com/file/d/1rodYfdqqMtgFTsFV2-KbSVDn_ywCqWmF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1xn11C_zZ1-hBeI6mjVd5aSd6Cx3ORBHp/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lA36hJUmOn4KWul3QmEwqWtWsraouvW1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1yIpYu1slV09cgdAp6PRR2QVtTVAXseYE/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OTi06Dge16dHJb85qDhtVcrpggaiAGG7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Iq91p62h32-SR2jhc22Ixb_xBnYCE1Fp/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RcOwd1o9uAG8uumna1cpViEknClUtVKl/view?usp=drivesdk",
    "https://drive.google.com/file/d/1dWLbTlvhvDuTOCy4TItbgT2b7zBaPcm4/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rWS0GmkA7jJNP_mgfEyHow0nAhgVBevJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Swz4BAzgEt-uu-Mq7mh7wP21rbPt4SqK/view?usp=drivesdk",
    "https://drive.google.com/file/d/1IAi7VPlpZoxYj7OeNKZZYknYIMKbX0e5/view?usp=drivesdk",
    "https://drive.google.com/file/d/1c9P2AXrEBMQGRPzH99aebEeE1cJTGrkT/view?usp=drivesdk",
    "https://drive.google.com/file/d/1PW1Af35-N6vMCsfJ4aYNIl8FNfuI9Mkf/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ra8J129KHx5jdBAoNElj4-bhFTs7IGbd/view?usp=drivesdk",
    "https://drive.google.com/file/d/1JALrQUlYhWni29ASzujuJNU9OYAdeab_/view?usp=drivesdk",
    "https://drive.google.com/file/d/17ilEhGrc9G6yaDAHPbis4_YAvQd9_Wlk/view?usp=drivesdk",
    "https://drive.google.com/file/d/1yu5xw5ufaypVWP0OnRE21tsfqLQRDKCZ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EXPbRtxh4pO_DH2rDIuuFzmHD42iTJTY/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_MTZo8y1xiMq0zuZsNxfAHVX9agOMEZp/view?usp=drivesdk",
    "https://drive.google.com/file/d/15naBcv5doIVm6BVJZb_NWzLRUKEqwkCY/view?usp=drivesdk",
    "https://drive.google.com/file/d/14-xnpG5TB_BquZre0RI04DNOs9bO1KvN/view?usp=drivesdk",
    "https://drive.google.com/file/d/1hourl97wvmirxc_gzc-DuSVL4Jk6JcH4/view?usp=drivesdk",
    "https://drive.google.com/file/d/1oQsAJXFDJ1ST8WyC1_59IpOdqIv4x1s7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1AZEowM3cdkY7xDAgLDarFK7harR6fyYK/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Y7MQN-Q2EgsjHut58qK1SBvk2S1JaaZV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vBjmCzhHjabJ9nf8K0ahN0Na_LJz1krY/view?usp=drivesdk",
    "https://drive.google.com/file/d/1TK223VB5sN3nEbWU-DRt6v8av4QcJfOu/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pyxwTTi4qtopA7G9n5L622AX0YTF0fS_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iBz0DraiAIXWiMF77ujudOrEBymLtoBA/view?usp=drivesdk",
    "https://drive.google.com/file/d/10IGhtImISc4BfKcoG2wi_TM5GVc7WeQM/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OEhJa-XOQT2QBt_vvBLZzgYPrm0fzUqo/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nk_sEKEbDY00nFhUecf9M7WjS6tTrSaU/view?usp=drivesdk",
    "https://drive.google.com/file/d/18Wpiv1NKF2NmS_3g7A6i5QuCKvLw23tq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ft6lCWObZqUZ44eK_9RWtNKHsth6mlwH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Od9MpT-t1GJOMRZ-QgWi0xl5icUEr-d1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-gUwMBp4kZJmgYuoMgPVRVpemm78Zxs8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1do-Ie5mmOIIsqDSGt_aTbN-glkleZXqJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/15FDbtNOsBMSzFa4YLDRMo0b2Jo8BuE3k/view?usp=drivesdk",
    "https://drive.google.com/file/d/19-mClpK3Pk_eHlBiAjFTnU2ed4orCnQS/view?usp=drivesdk",
    "https://drive.google.com/file/d/1yIgas3d31LCZDaycwEIjHx78raL1wDgV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1XQAbwA5oMNNfYkJ_V0YkJL1KGEyzM7je/view?usp=drivesdk",
    "https://drive.google.com/file/d/1X0NjEFfuyZ9pgS6KSh3dZS8o4Q7ptx3g/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nWknxptWZamaKOVLhtX98LZxItRxPUtq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1J3xGXkGZcUYEYqmRtXFO-XuWMLq301cZ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1O5VaBz989VpdLOZ8J2S6U_0bZBhJPfC1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1VOhdtYEhCJnPkpoL3tGrQkAy1vHfl9Vi/view?usp=drivesdk",
    "https://drive.google.com/file/d/1SMsrYM3BPyMHbJ7FohucagJSvBgWJACV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1u2GjGAYsFY8Vc_vn2D0T2ypbGENzF1C5/view?usp=drivesdk",
    "https://drive.google.com/file/d/14NitGwb4R3aG_hlTJ_7FKU0mVtWNHuSX/view?usp=drivesdk",
    "https://drive.google.com/file/d/1f7-NR26542F-7nmKpBKrY1z7i3WAl-aH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1E8plYer8eQ01Qsm4PvATsAyQK-HYKw6J/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cXzrdAQoGwaQfNAz26nBAbPS7MIvGoTj/view?usp=drivesdk",
    "https://drive.google.com/file/d/1mGGaTOHz_-WZs_iM2Kurdq55b8-V9ZYs/view?usp=drivesdk",
    "https://drive.google.com/file/d/1NjnNDYdhR93XyI5AbVH0fiSwMr6vVmZY/view?usp=drivesdk",
    "https://drive.google.com/file/d/13Wmwg4X1vFgZVBTl7SV1tIVJU15AWb8G/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Q2XTwYtwZ9QMbwihVPQSs3R78Bkb69tr/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vBPLcQKkR-vBpjt_JwqgkgqlPkkfeNjy/view?usp=drivesdk",
    "https://drive.google.com/file/d/17ZfWFWHEvcXIODKevgcayAAl9yocuKrb/view?usp=drivesdk",
    "https://drive.google.com/file/d/131kN3iohfvpXjWI9QlS1qMC4s-FRw63I/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CE46rxxSUMhg-f6g-VOd5xsPdInVvafH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1fsvUxZEtG2zwQ6bjGD657RkjAUZMOaFL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Pg6bIbrUnjCQFaX6zQlrPfX3pJFketJh/view?usp=drivesdk",
    "https://drive.google.com/file/d/1mXoFj8VqayXBawQHNzwnKxjo8T-6eBaB/view?usp=drivesdk",
    "https://drive.google.com/file/d/193kY1DxWzdblMikcD88sR5F5IEIWX3pH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1UhEWxPwI2836JytLcFXx3yIE5ywKlBhq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Qwud7lZbB4PWwn611Q2HxycDXYW2CKQK/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vZxAuw_vLb6WKxJmB4vpF1jYpbIykeU3/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vL--TWHwCGIz4LrT9DC5QgS12tp16i2V/view?usp=drivesdk",
    "https://drive.google.com/file/d/19Wfh6N_7sPn3C9xfU6TlrLwzrFKOh9Eb/view?usp=drivesdk",
    "https://drive.google.com/file/d/1BR_RUuFp930npBRXuPnajLXGLtGzSRXw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1My2EV72AJkeGRvfRvwhh_IczFVK5_udw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1KUf5zRe1X6wjJoyjmRW-WvnhZw3_IZfn/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_EX3PPFmDGEb-BnvuuLxUSuJshZHAiG4/view?usp=drivesdk",
    "https://drive.google.com/file/d/17py4b1XlJOZUuI_5_cnVVfuMgEnUXbKm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rYcJ950RRLFaGaGOP2oGe0vq4TcGLdmY/view?usp=drivesdk",
    "https://drive.google.com/file/d/14p9uW2AW9HZNgYmy_akCxzYsX141iKF5/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Zekcj0RvinfI-JgVWNl3GGbqX1BRkt2D/view?usp=drivesdk",
    "https://drive.google.com/file/d/13j1GewOqgoEnPkv2CmDRvv0xDaZpzYRR/view?usp=drivesdk",
    "https://drive.google.com/file/d/16FFwKf1nYeCjdlIpDHwmwgaX0Zq9ygUw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vZOusdJCkZj7AuYmzUJLw-00bMQidHSV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1VVe2qJEFDYjmIiC7AxZu5QTVAcOG5VF9/view?usp=drivesdk",
    "https://drive.google.com/file/d/1aflRb46WOHaYMQ7JOH_TxcMo_BPIRPn9/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Vglz3CPQnFttG5hOVvUsh6vIOFpJFvE8/view?usp=drivesdk",
    "https://drive.google.com/file/d/13xTovuAjGCY0HV6iJbCpL9q9g0uD7lvm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1I0o6h2ViMKrH18Kd_dhPX65QiMh988JW/view?usp=drivesdk",
    "https://drive.google.com/file/d/1D8YnuV3TVfAb4m1gkrsFkYfCoYp9HG74/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ShdOQBtU-rh8PALqjsZSzE8IeS5p4t2l/view?usp=drivesdk",
    "https://drive.google.com/file/d/1amdqpCyT3G2lFyPG1v5IKmOGX_cieR2t/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ACZniRC6UlOysl4uXLXjybtL7jwCOjlf/view?usp=drivesdk",
    "https://drive.google.com/file/d/1B_hs2orYkVFp4ol04WYatT6IzrTJnMbb/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RUdhXjebs39j6QhxcjM5jGF7Q8mTvxuK/view?usp=drivesdk",
    "https://drive.google.com/file/d/1S1MigCRWVQUHOoi2lQjNQeVVAhR_EpGl/view?usp=drivesdk",
    "https://drive.google.com/file/d/1FaAuNMwgT-8-Xsrvyk7kB5_KhJFEBMiY/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZH0Ntdwq-GDDlpgmFkiirj4Ah5pt2GSs/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Hgl5JgEJWrQryPYc9sLpE2KxwUxCt8UM/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Fpwd5rSVUvNBeuc6udPszaJBgsd1adkA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1TXQ2ZoQOSpR0Ec9GE339xu_McqmBEWsy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1yZpZjyaMKUJcyNj3ATKc4ekeZD_TytUy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1C1CRYdpHComDOrc2WnCyX8amxCTQr6iq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iNmXYyn1CFwMuNhED9YAqe8jCYloz0bq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nlF8jzenNznVJoP-p1y1N5vEN0ToUu4q/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OsxYCDhFl_4IMDcRwy8TY1W04KeeK63S/view?usp=drivesdk",
];

const year2015Pics = [
    "https://drive.google.com/file/d/1OzlVgk0FWXmNu4NaeNVGBkxf8GCSTKNs/view?usp=drivesdk",
    "https://drive.google.com/file/d/1XRzGoJBAJ23uZ1u9Su7VShN8XmnoFZE4/view?usp=drivesdk",
    "https://drive.google.com/file/d/1y_xSj2WXJ1PIHs6w6SkVIn4JijjK-Sby/view?usp=drivesdk",
    "https://drive.google.com/file/d/17xGOe9jBxKMUdAvcSeAuX-cNVA_RrAdm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DRCu5yzL5nmFJyeKCQQHphAVehwvrIPu/view?usp=drivesdk",
    "https://drive.google.com/file/d/1g6S1S5LEG5oRWKAHvIabO4D8gS5owXmw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1mARoKeolpWyTRcekWBzul2og46ZyQpjr/view?usp=drivesdk",
    "https://drive.google.com/file/d/1FXDL4nA51f-1ITQQhAMEX0Mdi6R1oItn/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ajfKhThbK8qiVrwV96ZgBvFHATpNNv4E/view?usp=drivesdk",
    "https://drive.google.com/file/d/15TUzoHaJaW-X2xv6noHWhx5hbYT97_F-/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MIKde9yuLNF2Qu8xA4BPOiO42zkgCsHJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1hn0u13ID0wJt7XoX-QHAPwq1nOvn-1xB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1NU4DMoXIYG7KSoA0YOVEI8g5qOObVdPP/view?usp=drivesdk",
    "https://drive.google.com/file/d/1P_NC4o-diM9OtXLcx6TwIFM1C2MoU-GN/view?usp=drivesdk",
    "https://drive.google.com/file/d/1brgfoGZSJ4T3ghn6s_xPC4NXL2EQkwA-/view?usp=drivesdk",
    "https://drive.google.com/file/d/1wADXuORaOY3bS1g8_ZxkeR3zy-gITJnL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DX2llX0dz7DszP-_WbHLAPiL6mHZkb76/view?usp=drivesdk",
    "https://drive.google.com/file/d/1B0MVgbqkbe30afkiYZmFlwiYWgpatRoM/view?usp=drivesdk",
    "https://drive.google.com/file/d/1D8pOPjU-IsDyGlzDroqPcrq_OWpCY2Kw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DBE13cu-GfeuJ8wBhHEhZRpmlTo9dxzP/view?usp=drivesdk",
    "https://drive.google.com/file/d/1SwDeKjP8yfvMa4XpqgsFjh_yv1sM6Rld/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CqmATQ-9xZvGSsJ0TskK_xbFAKOvfX50/view?usp=drivesdk",
    "https://drive.google.com/file/d/1BdYspH-_A-GqxoQQ4jSZMyvWam5-7tXy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_B4r9gi9XycSqIrkE4rMqMADEw162nwU/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qSg9Z1W9g3ZDR5porXegXdKmNI9rzVd7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1JJLY52Y9PRJNSg9cEFBYkoRHGEVq9RDT/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Y7R2reU7ZHK8n0u6UlCPkziPsDVQ-lVS/view?usp=drivesdk",
    "https://drive.google.com/file/d/1bTz-gclmzIpgX4574vsq0-_-93Olo0l8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1t4MwTnAShLVPg1opOW59kDGcz35Jrxil/view?usp=drivesdk",
    "https://drive.google.com/file/d/1IVELOgv7u3FNebryuMXHInvYcm34rWZ2/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Ta10KTUcwyq5DBQcfMJ4MM4XTO2ZfsXB/view?usp=drivesdk",
    "https://drive.google.com/file/d/10R9QvF6kMxjIQEQ9UGJCUvq5yuUBbZLL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1zZN9nif58TzhqtLRyDXY0iF__sLvCuYf/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Agov98JveGfc-bvOPdnTvcTujrsZfb_1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZoloJK6Zsp1xKOtcBj40ZM-FmdzPDn6t/view?usp=drivesdk",
    "https://drive.google.com/file/d/1M2H_82NKhal3NmfAStsqNeib20PJClbd/view?usp=drivesdk",
    "https://drive.google.com/file/d/16pq1qtIFisdREa4XvcY8nygpM42SqpXW/view?usp=drivesdk",
    "https://drive.google.com/file/d/1LW8AtrECJu7e2Cz0YSCqABeS_9mLfvHP/view?usp=drivesdk",
    "https://drive.google.com/file/d/12pgJTuUxmwfvjBqUIV80JWT-7QTgntDF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1mOWX8oAfHY1sQY-3ceswnhTuGrycvrpy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_mu6xOcapzobUj0lhqYTiMwFZ6XEUM8L/view?usp=drivesdk",
    "https://drive.google.com/file/d/1m75gvK7Yv7XW9LErk1xe4AYrHDUVY8od/view?usp=drivesdk",
    "https://drive.google.com/file/d/1FJNkcrhx8Y3QHfNrek2xZgZ8tazbK7Gx/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Ve_ep0GzK1xCy0i__fWqRDhbF1I2D6ei/view?usp=drivesdk",
    "https://drive.google.com/file/d/1LeyhdencBW2FXPmpu58uNUUQj2F8NVv7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1UTdDsk0l83whKDNuDJ6I1JzWdVnuc6Ut/view?usp=drivesdk",
    "https://drive.google.com/file/d/1sDBMNFZtZTxsZFv06-XeeyhgWh505ZkP/view?usp=drivesdk",
    "https://drive.google.com/file/d/1uF9WV_lXIG-YHQW8cCmHsV6XIOqO8dFo/view?usp=drivesdk",
    "https://drive.google.com/file/d/1jlhq85ab0HJ_-z4Xhfuhe_75yY1lXgzf/view?usp=drivesdk",
    "https://drive.google.com/file/d/16NxNTOd0iBK8m8kdKwEnpRj-XcDBjRpR/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-ybHaAzUDR5jRry7dPlSE1PNIa-P5zmZ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1bmgCt9NSxPu2eDemdngxd6uTM5WXrsfQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_idkivt-SBVMMYJ2sAcGXDJZ9NWsYu1w/view?usp=drivesdk",
    "https://drive.google.com/file/d/1q-KRFiWTDoRTPYmFQ0V9RoeQhWCdoB9o/view?usp=drivesdk",
    "https://drive.google.com/file/d/1dRz-pXVlT4gerLqUBySMtcg6gm1-c69_/view?usp=drivesdk",
    "https://drive.google.com/file/d/16qOqZLLpnqONVTy2LDXfg3HpjDTO6gCj/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rjwBgr44ZPhiRJg4h1qU4-51mc40Gjsy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1bOkyCLYZb2C0JFCWbecJaR7Q9DB05mbq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1J1U8AugOl1I1bV7Vd84vFptKXAb9tYP_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1t4o9Qx1wSPKyAMJRudAhpYDO6m3V58XD/view?usp=drivesdk",
    "https://drive.google.com/file/d/11fp0tgEs7bi3vlVgnDQFx-bM2HeOpRxM/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qZ3U-iBraHP0W-HUsApoDoRSFbu-G28d/view?usp=drivesdk",
];

const year2016Pics = [
    "https://drive.google.com/file/d/1ZxlM4tMU1NinCW08wpoPOmu_DO0cDrBD/view?usp=drivesdk",
    "https://drive.google.com/file/d/19d3TdF9tEJSWqwuzWswPzoEnCMFyn7vW/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RcczvNU5kkuhZPEPWdLYzdSgIUPx9Imr/view?usp=drivesdk",
    "https://drive.google.com/file/d/13UqjEPYaZ7XRqnHN_k9Mlte65-b25hdI/view?usp=drivesdk",
    "https://drive.google.com/file/d/18mLBOIe0kybkgRRDamTKlF3Foyqso7p7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CAEE5Lyny_4c39SrZzM6GkEnns1exWpb/view?usp=drivesdk",
    "https://drive.google.com/file/d/17rhSPgcGe-xoEJJ_MmK-66n1Wfy5v2V5/view?usp=drivesdk",
    "https://drive.google.com/file/d/14qhpxTp_orLozTQRpiu2GsAEulMIa1ml/view?usp=drivesdk",
    "https://drive.google.com/file/d/1UJvVjwRdaKYD_a60FBYkFoiMj5G3l-U7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Uc1W5JnycGps0HqQgDHy5oTHR8XZAncE/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Vm_5Pbpt6UI4DLTT6r3YwlNoCE5GdTV8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1dgH3QSm892F6x3w3qPkN6O3B8X-1Mz-s/view?usp=drivesdk",
    "https://drive.google.com/file/d/13L80aW4kRXM_geVap0DvI1yJ6XL15q35/view?usp=drivesdk",
    "https://drive.google.com/file/d/14cXZGfSgpz7QWPDKhGfBLlmltjyQZ0P6/view?usp=drivesdk",
    "https://drive.google.com/file/d/15Yz_PDwafrgX0RzhW9MVf8QRC5FrJ7du/view?usp=drivesdk",
    "https://drive.google.com/file/d/16dbaZrfqldeWoajySpoFAyeoqIS-_wHA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1C8Yg0N7cpi-tkD5Zjk8rVBc5Z3MD4qYG/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Hoee7mevTVozQIBVnu8U53AYCAhY3NK2/view?usp=drivesdk",
    "https://drive.google.com/file/d/1N5f1LUJElDN1PPq0Qnkhb6A0UBhcHMCL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Rgo3PAuOw0qIQLN6itGkS5UNMX1mLm_O/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZZIHhP_7iDu2KhOQM1XBpJXpWrJwjDcn/view?usp=drivesdk",
    "https://drive.google.com/file/d/1k5597q2lCbjscVLSL1_0ZdqitlKJi8Le/view?usp=drivesdk",
    "https://drive.google.com/file/d/17KjkEUKzddbJtohxXfXlthzdFH8FCKAB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1LRLgCnJMldcIit8c7J-eEsXKxjlvVq7g/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MSh27iEbUAbMpKeK9EgogLRR1mhOf5gG/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ckqR-eaH9s0HWIzMsQOiW5Kn_wveZzxw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1t7b0oyNsONrK4aKo4ELWeeSzZW1ve1ZU/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ADxcleDPxw0QLvlJUpVHYmKLlZLlOkfV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CN7TzVXCTJqn3SeHtHUrpTVwzx8EoAgN/view?usp=drivesdk",
    "https://drive.google.com/file/d/1E3iAJvMfSfnEILVxM2xEb8OmaRJym9DB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1GegWzHuGZuOApNTVOcEZBjIG8A9rBS7I/view?usp=drivesdk",
    "https://drive.google.com/file/d/1J3raaRqHpzMC_f3mx5Nop-7aM40vVmTo/view?usp=drivesdk",
    "https://drive.google.com/file/d/1P6LIQp1HL8WVBQ-0LoAAMLWt2WRhE6CT/view?usp=drivesdk",
    "https://drive.google.com/file/d/1VI1zpcYWit7-z_lB7gKK4xPIypGyiPop/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Y-pCJZtk3y6WMVXglCL1RRv98bG2YI_n/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_raLP8nOiAnnMGv-OlCMa1N5o-8ER6ej/view?usp=drivesdk",
    "https://drive.google.com/file/d/1d1G70WlZNr__VqAcmL0a8wnEBwgL2Enx/view?usp=drivesdk",
    "https://drive.google.com/file/d/1dCdufzGic4g8Mfi1CUjC8iMezsxTuz9k/view?usp=drivesdk",
    "https://drive.google.com/file/d/1j5Ueu1Cawc6ZZVKSLk-B209vM7QWbMkg/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lMcH5LbE78sQ7Mv9C1Fnok9M3-BJ7pkT/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lgxHD0Z4PB5r2nxNEBxqJS4sODbMYrix/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lv7b2JyhVZjRL9JA99Si7m-T_Ais0lum/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lzK0mEboswUCtVkFDGegFGZkYTl450Y8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nCCjV12zuz5VRbivlzwumlP-re3pBTFX/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qKibwwQyPf6Cv9a29X0dfrCZDE3GsG0U/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qSSuYT-pYHZh83jfp1ZhlMAlW_UV3r8C/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vWmUPIniBHAqxSlKmhfPcqQrwdjwdrw4/view?usp=drivesdk",
    "https://drive.google.com/file/d/19Tuy19ELbFpE-NKYoSjceRH-0eIursLQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1IPJyj2jrUrNMfYvhOMTalZ3-xO2omYdq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rRmtdh1sH4GhOOq3YxIMI9kf-u4oiYvJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1w70eA4p7GymiBFmQZKGNSs8LCQ9Ro0fi/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-DSt0MwcaIcD_N2wbnEQ1YmyUnYb52bQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-LWya3wDilDSTXKWTgkFNfBRrgPIcwiP/view?usp=drivesdk",
    "https://drive.google.com/file/d/15d_nWnFhWej6ZQjtULosn3ji2wMnpkUV/view?usp=drivesdk",
    "https://drive.google.com/file/d/17TVmtiORaQRz4iIRicLCXVqFrHGrip_N/view?usp=drivesdk",
    "https://drive.google.com/file/d/18Jv8U6FI8pI9UVClTT08OhL2cXKiqi3q/view?usp=drivesdk",
    "https://drive.google.com/file/d/1AZmtWYrdHRr9kVX-y2dNNZ6zL9HWtnIL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1BIsZKEiPeEotEnPkJokCWVrM_u8FtEY3/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CqBWBhj0_miOr4X4wHBGknasQisqvIkc/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EAzqL3zlzCIOHtRw3SEuLZNrZcUuKCp8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Pwb1z2SP2V2WRSXUYu3R87PqXPr9PXQc/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QoT1J9Ru-tO1X-s0ETkk_OkEFWoDXcNe/view?usp=drivesdk",
    "https://drive.google.com/file/d/1aUHZ3T1GzpEj45rlVAP69QUgSOHg5or8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iwpbhmJ9tojY-L2T0pDrR3OGCs4lE4j7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pwmNs4k_9XwCkDkDPVHBrwldxtThHCHv/view?usp=drivesdk",
    "https://drive.google.com/file/d/1sH7woI9gZ6Te8qCw63kvOLl9GWX0cAdA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MGn6rJAWTawD4xxTBF90mm0lLXlqDBvq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Ry85zub-rqDZxdMXbJEbLbvoCdBsiRe5/view?usp=drivesdk",
    "https://drive.google.com/file/d/1S3eypN8JKKyFUH45i-Jm8SFZdKrjFP9x/view?usp=drivesdk",
    "https://drive.google.com/file/d/1b2llSNtOpI8fXLIZuoaheZLU0PLmehAI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1eQ3LI_xPbDk6WoAp7Ma686Mgw0UT-nyu/view?usp=drivesdk",
    "https://drive.google.com/file/d/1leclpFVjYKgPJmjPE-Hmj5tEo-FjrcAy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1m7c-zcHm0PWTQz7jZyG_rw3Ooq-FwB1m/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rdLunWjdhVMVD3rCSFqVPILFnXlEIw8v/view?usp=drivesdk",
    "https://drive.google.com/file/d/1u6QOvBZtGNWK-DW2kpsGEsvkthDsS2hH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1v90JgWx19ZugcpxcdAFxamFFDGh3HcGm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1wd56dYGDjcGB7NAf3JPHxutRf47Pfj3f/view?usp=drivesdk",
    "https://drive.google.com/file/d/12Bf4GOFtEsHXWGCgQJoJ7Wmouy_DrBVo/view?usp=drivesdk",
    "https://drive.google.com/file/d/179GxAKx4NpUokARnmkRIsIV3IqxqbvE9/view?usp=drivesdk",
    "https://drive.google.com/file/d/190mV6Ir4LBl7yvpZx9lEePQuNOzoNYH7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1UzGmNTZtCu9mxfaRwifA_2efU9QLaQ8x/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZnpTTTlhAPjGlTiaSVbSRkWByoXdfXzB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_o2cvCbgQGlPTm8-JTsfB45fxGNimrRf/view?usp=drivesdk",
    "https://drive.google.com/file/d/1eSiaQJCijlI-3uwRARW4Q1ZY5gUjQco1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lH35mMPOHqfzDL3jNoXDEGBZbMYpUGx9/view?usp=drivesdk",
    "https://drive.google.com/file/d/1vaOx86xKRIdk2zg9VOnfm8fza2Mg9NI7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Tb0flwRe5uZqOK3V-o86AVeRtK04gTLW/view?usp=drivesdk",
    "https://drive.google.com/file/d/15SmditKwrDscvt0igL_Qs2qgcMF-w8CO/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cfgiDmmoHN0K6SZD5PBNI5U1ExVA6xRS/view?usp=drivesdk",
    "https://drive.google.com/file/d/15VWwbyQ7nkoNoiaAZfjb5EWPEAuzmFMy/view?usp=drivesdk",
    "https://drive.google.com/file/d/13xuerzxv_lxRP1AX0zcjLUZEBASxBijg/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DC7YckG8s4HlSvBGJ5Z9W26Yd56n4OiA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MDmb0coMWq3nUCeGR4e1ChlXM42C-GKJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MVtijb-NGMkTsMSMyypkDy4CM1sFr9hd/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QGGW32o_G2-CgbOEdQ7dK922IjbATgjF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1jy1xJmTwJi8-Xd-HQmO4OPMPnU7CUk4S/view?usp=drivesdk",
    "https://drive.google.com/file/d/1mB_jGZyIG4DxVVpxYFippKapCb30iwRA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1scjNEn0Dp-8EUapzritRp-5Ela9VdufI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1bhhirKhM4bj5MVmOpJHSVPdM-x7Tku8t/view?usp=drivesdk",
    "https://drive.google.com/file/d/1GFAe5l5a9xbgsU_bewjXdjSDiOeqchwy/view?usp=drivesdk",
    "https://drive.google.com/file/d/12eg2DgQgm-US-8-w90YfkMuNJb8SmCt8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1718XLVpJyfQYqFCx4C9M0IhszMbRylKt/view?usp=drivesdk",
    "https://drive.google.com/file/d/18_1uFcki4owgIAdZXTsxlLrWNGHeSipG/view?usp=drivesdk",
    "https://drive.google.com/file/d/1AXBvWBSTIsobHtd_M8-0mB99HUPtsQ0x/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DvRP4E0Zw_nqfYY3ijAQZt05vqvyHp2g/view?usp=drivesdk",
    "https://drive.google.com/file/d/1WWyYNl1YUt_JK2KzmsRLy-uqJNJGbE6-/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZqcyPKqucqLpXfS7GYAbHDPyMmVZ3tkp/view?usp=drivesdk",
    "https://drive.google.com/file/d/1a4tLXTiq67lNHDaGxir_Nz7ECIrNuT3y/view?usp=drivesdk",
    "https://drive.google.com/file/d/1bB0ENwZr35cTKZmALPnav9feadapebwF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1jZ3b25cF_C5fnjca26FQQ6JR1KZsR9bo/view?usp=drivesdk",
    "https://drive.google.com/file/d/12qJCPZj2dJT6Skv34MBmYhOR0TcJAVeE/view?usp=drivesdk",
    "https://drive.google.com/file/d/16mlFbu-L1tILstpDEJb_L_jxk9k4uTLI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1A-VvRb5Ivsc7HtE3W7Cq41NcVDMVYoJv/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EWdSWSzJe15db2Oev3E7BYquWCUQDTZ9/view?usp=drivesdk",
    "https://drive.google.com/file/d/1N_31tsYgEXjUX6reOj5SseLWhjUH-Fow/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Obt4zyuG8QmVFTf0UH2iwI96u34TKoDU/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RQfUGgHTBiGERGqtQ91_z4z_c61aqyPY/view?usp=drivesdk",
    "https://drive.google.com/file/d/1YWopCrdq-fCA-oTwAgl_0-D7FJHpbpRO/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lYu3CxneWan8Te5JjGlw3e2tEgSSGVFA/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nMoOczLouGwu68Li6QN01hjOXdgcco7I/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rxmuLPXiFFCAHlss7JjsltyupEiTJqzH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1xcONDmCdlsqmxZaea3PlSZ_dYGdk3XCJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1y_hk_-29dTfLoTZaRzZJt-Bb-WGwR_vI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1f6iIrsoaGhw4Re_bOu6MLJKJV8CAag2F/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pawyPc3xbGbXxdonPJToh7h3K4ejqIJx/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Wmzq7HoSQfqZLy43wtRj4QeAHRy6cQIt/view?usp=drivesdk",
    "https://drive.google.com/file/d/1UY7d2cZ8K28OEOiahRjAndFTsxnVjTdq/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ObkAEsB2XkcH_s-L-VUqbPwSWAZxFnYm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qllBLHXd9cXS2axnyHD5VjUft8mU_yWo/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RfvOaOSEKFHN53cwJCyKLkFUghw2Hcer/view?usp=drivesdk",
    "https://drive.google.com/file/d/1F_oAjnypwagvJZiat1CbcWEJu9cl2M6Y/view?usp=drivesdk",
    "https://drive.google.com/file/d/1eKUr-e3SIJVs1CRJtGK_bd-QX0liO3WY/view?usp=drivesdk",
    "https://drive.google.com/file/d/1j-uixr0mD6hfVevaDA4Vrd1RO0c8qrom/view?usp=drivesdk",
    "https://drive.google.com/file/d/1U3ICD49kB2mphdgpLI2wIWMy0nt3ObTs/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qCZCiHoZfQFi9kSuxPLIDBKM9saAgEzk/view?usp=drivesdk",
    "https://drive.google.com/file/d/1FM6vDh4I9Q7bJD4O_1ZmohW7m4cFCRqm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1j9_WwQ4bS2tDNKX0hVNAXRj7z8hEN7xI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ADbh_IB6DlBpsQymi6_UOBe5rX3Il7_c/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QXtYG0zX2dF5egj77AtnZWTisW-iAjXC/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cn6XPj51fpp_qZPo0xsYgN_c-VJe-MDd/view?usp=drivesdk",
    "https://drive.google.com/file/d/1V_qGfnFAxBoelB_RRuiWSYzJ0Ig_XrBx/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-PoEJFPOpe5sWYtH_YrKUd3JodTdVwlk/view?usp=drivesdk",
    "https://drive.google.com/file/d/1m7cPD2-WmpDFDR6c1XuZFSsqnxKJu9bB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1xagt_EzJjIEsnOfP5ukre7J4gNlpgfV8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1tgNprT_ULre5SQ_EqcxhA5MGbVCjZ5Jd/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iXKuHLAsOU7oJvxXrNE4M7Z2I4dWkK6c/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MOC0BW4tDN3YdxQx3p-Cx8lWffV6wAG4/view?usp=drivesdk",
    "https://drive.google.com/file/d/17YkZfVnPt-xVryFJuuanpNwpl-zVW4us/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZHlF6TvUW12H6dmtBwbfNlYYOfpb71_P/view?usp=drivesdk",
    "https://drive.google.com/file/d/1IIOZx-xhfnt0-K5OhCZjTdpbw6S82wUr/view?usp=drivesdk",
    "https://drive.google.com/file/d/1TQzX4ONUhMt3UoR94udnM_UfMSUBK8vj/view?usp=drivesdk",
    "https://drive.google.com/file/d/1MjCsbhVyuC-feXy2WWclf7rhnhIVJede/view?usp=drivesdk",
    "https://drive.google.com/file/d/1-nyi4UR3nYhpaX1ocDzIxQ1fmkJIoAv_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1jgh3vpqYS1TWVKV80hGWMDqQ1DWyYCYB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Nta-addD1BY61V-RCeq--uL8sOiO72XC/view?usp=drivesdk",
    "https://drive.google.com/file/d/1qXuppanG0-zVIQbXPnL8HmbXC3JQtFKT/view?usp=drivesdk",
    "https://drive.google.com/file/d/1q2Ab9b8eEdd5KPqyqNXbk5xTcOi3JzQQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1u1AEbOerurEdiqNyj2hsEwL5-sSGrf2B/view?usp=drivesdk",
    "https://drive.google.com/file/d/1kavj47hT3irYTNkSyWehP13SfWwOUI9f/view?usp=drivesdk",
    "https://drive.google.com/file/d/16OX7ZThRudp1_8y2BKrw-YLKmgzsZ40Z/view?usp=drivesdk",
    "https://drive.google.com/file/d/1f7_8YOq-OG9Z7Z080keWnuif5KCpQ_1q/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cMwt6iUba-JJtoGz5Likt0cBxqVWMVFC/view?usp=drivesdk",
    "https://drive.google.com/file/d/1zfMxgc56iO7WUr0ORmgJ442AL9tw1YM_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OaqMT4JPQ_TzUy7DBvGCRJXBSB_JtJgm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1134k3AsB8JcaZNH5e3iluGIVsuRCf0L2/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lqwQh3Qu2wIqhl6C0DK8mwios7k48zJy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1xNCCtOGh5Yy8_5O5H-H8MjowEnP2eMJn/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pqdv_pW0ywrSjUvMdYqUIe7jbOSjVqvd/view?usp=drivesdk",
    "https://drive.google.com/file/d/1HAoZsE-v7Mq3p_IIU0h-8wy8QFhqZJSh/view?usp=drivesdk",
    "https://drive.google.com/file/d/1HGYWLVpP2wH8XgIYPyAsQxaWoCWrJq4F/view?usp=drivesdk",
    "https://drive.google.com/file/d/1URaffDu-UP2_Q3IEHN50wcoX743Le4Il/view?usp=drivesdk",
    "https://drive.google.com/file/d/1AtjJsgRcqKGymrlORaR3ad8q_keqYZNf/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ghT5oHu1fnQvH4gCyMcGomaDw0TTa9iK/view?usp=drivesdk",
    "https://drive.google.com/file/d/1f2dVDlJn07yvd65mR0san4Ov8kawml9o/view?usp=drivesdk",
    "https://drive.google.com/file/d/1lkwWDV5PHXFdbjjVwbDDU1Nr5XC2sYBa/view?usp=drivesdk",
    "https://drive.google.com/file/d/11VKG-CBkQSCS7yupStW7j1PFuUagH0oa/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EtK3LHwEOEezbqtQWpZgAw8LFupwTqOL/view?usp=drivesdk",
    "https://drive.google.com/file/d/1zSGM7o5QT-B084U-ftmpLqUCaTltvrxS/view?usp=drivesdk",
    "https://drive.google.com/file/d/1f-IMhp6J_AynrbYawPg47PUVr4TwBhlw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1aYbgMIcBC3-tG5LS0gi-dsG1fTdAP7m2/view?usp=drivesdk",
    "https://drive.google.com/file/d/1gLFKmP-kH0Zw9KiYXa8v1jHQtO_dHoQj/view?usp=drivesdk",
    "https://drive.google.com/file/d/17AcWZ5-kRjEEYSoIAgGcmZPEMaPiHXGs/view?usp=drivesdk",
    "https://drive.google.com/file/d/15Lz_axQDVJ1Wewu71NuNhSGcUidQNrZu/view?usp=drivesdk",
    "https://drive.google.com/file/d/1owO0xrRCRZC4y3yjUbMPuNEAWDL7QWiJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1aYXittmUMhbwX4ixSxcCl5uo3ZpuTKBX/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ysFcn3RKkCtTpSnyd-39AWoQs-WBRzul/view?usp=drivesdk",
    "https://drive.google.com/file/d/1riIP8blJ_Vthnf2HzpNOPNWTMjOj2lYv/view?usp=drivesdk",
    "https://drive.google.com/file/d/15s3kdcunvoRH6IvBnjUuGkswUCBybeHg/view?usp=drivesdk",
    "https://drive.google.com/file/d/1asQsDRePW3qILXmKvmx05sO8c-_XUcH4/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CI988Q_JlhQBP7CY00_qjPV0wZ5AN7r-/view?usp=drivesdk",
    "https://drive.google.com/file/d/14o3-WwpMJTBLgYsgrctUzYvxF4AlSc4T/view?usp=drivesdk",
    "https://drive.google.com/file/d/1kJocCMLcM8sQt-ijS_MsxeYvxpcZNdCO/view?usp=drivesdk",
    "https://drive.google.com/file/d/10ZFBdsLsc9SmO8V4IvrTXbuyBTHExi_g/view?usp=drivesdk",
    "https://drive.google.com/file/d/151ShdD7MVwmQ4P7ToB-UHitlnGCWMfOe/view?usp=drivesdk",
    "https://drive.google.com/file/d/15MkP2wJ5D1kG6SO_AZdKDKHOEmlj3sMZ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1e2ur5ancqiy-eRDCcoxVvJU4W-jD7Seo/view?usp=drivesdk",
    "https://drive.google.com/file/d/13Vlf0wWrxbcDi_Q0-MgegVxOAEzO0M7N/view?usp=drivesdk",
    "https://drive.google.com/file/d/1y0M7NmDb1uKk_HsT8W5fU7oMdc75r1x-/view?usp=drivesdk",
    "https://drive.google.com/file/d/1oZu1TPBJrfP6-K8p2hvO4m6dcZgmFbMG/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iD9wd1VHR-bZFFlyhD6rVBal-EiIpH4V/view?usp=drivesdk",
    "https://drive.google.com/file/d/14edxyIIf1hx0oLpwTY6TDK2oyxjKoiUg/view?usp=drivesdk",
    "https://drive.google.com/file/d/16bf8CBNQTmbJmsp9YFFn9H-gXDBlY-5_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EnAOYI5QR6N4mJTwa88LbcPC2Yo0wPMp/view?usp=drivesdk",
    "https://drive.google.com/file/d/1fg_OpPckMw7-3MTWMwCl4QNjNgNFbJsH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1kouqdYlpfNGKJgoSQmAVZQZJ5mc9QWxU/view?usp=drivesdk",
    "https://drive.google.com/file/d/1z_gdO8mFDe_RjcAUNyzj3iBtqMi1y2bB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cm0by35Abihg8slFWUKRl86Kp8IG-Upy/view?usp=drivesdk",
    "https://drive.google.com/file/d/11DRJIRk7ZSM1QEnAmbyqKOvoX3ZzVbyw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1dXkue9TkbYGeovZHolxxBK_y7pb2UGHd/view?usp=drivesdk",
    "https://drive.google.com/file/d/12VqVBl7cfmafEtiZO8UEtQdmauqFCj6x/view?usp=drivesdk",
    "https://drive.google.com/file/d/1T4cj4d8SzrtmOd5OpvBgP0r1mXTnJ5KJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/13DHIr5nYaKqSvo4xuALVHdpWcW_eKszc/view?usp=drivesdk",
    "https://drive.google.com/file/d/1KEheP9BHhl6nvSGcjow2dVh7mMg-Ltbm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pV1J210giptJvT3pm-yrl45qH2GXtDmU/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Vk_6d9eeAvTCufst7q-A2MOy1omMOQiZ/view?usp=drivesdk",
    "https://drive.google.com/file/d/10npMfSLHKirlc_S6JzNPKsgqCpKCjHRy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1XWp09EB3gRfHKql9Z0iXksP61yj7BgWe/view?usp=drivesdk",
    "https://drive.google.com/file/d/1KgEeNu8OCMarOPBwUEOxj3CyqywhDAse/view?usp=drivesdk",
    "https://drive.google.com/file/d/1VTl49JKgcj-pTcCpaADVICjxSSyToLxw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1GH3yXn7mkwfrKRsVEjTtH6qyRWacOkuy/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nu46pJqKonnN3V_kKveTM6BhJmaM6p4_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1pVtEYnKroT0bovuG4tuFW43LraL7bsWH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1jMnI11tkvu3O7l4EQPTAwc3wddad6KWg/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nsSJPh4c_tdcCNghweiKTCDrnpb029-U/view?usp=drivesdk",
    "https://drive.google.com/file/d/1fL94hKmLGRArw8mPzJHhGDW40mWpz_LO/view?usp=drivesdk",
    "https://drive.google.com/file/d/1KBjo1EjoJ1Zj0le66hYMKBMVH9HZN0_p/view?usp=drivesdk",
    "https://drive.google.com/file/d/1nchObV0BbAJ2hNr4Sv2ZY5Kd2OzhUCwQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QfR7mGvuz9SaRlUvMjMC_vciTBqdcVZF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1CpGmxHNey8_tWLCq8DyoROdjnoRU5y7s/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Z7H70qGzdPS9bH-A2-4K4SY7RgSuRSo1/view?usp=drivesdk",
    "https://drive.google.com/file/d/1JDMIcra25my693MezhtDSVPwJ5TXCJSx/view?usp=drivesdk",
    "https://drive.google.com/file/d/1cpsQ8SwJKx0xMLChznXZ-jKbd47E-lfc/view?usp=drivesdk",
    "https://drive.google.com/file/d/1phTjEU9HXphsczGuH54hZs8us8DxQics/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ljqR_-Npg_xLk0vvOa_JaKd1WO92N13N/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QKHQkxkMvU_Ars9282R0nK4kdUPiyrVO/view?usp=drivesdk",
    "https://drive.google.com/file/d/1_7A2S9CDnHq9vqO5AFLF--BXSLCZwUMm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1KMhppmCr7teueKOzBu8X8jaNZqdzIiGt/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Vi4jbU3xZsaz0T40ngur4mvo1rJi-zQI/view?usp=drivesdk",
    "https://drive.google.com/file/d/1J_O7Mgsnbs24MeoW_Mhv3SFF7easAZU4/view?usp=drivesdk",
    "https://drive.google.com/file/d/1iDvOLM80TvN7YT_NOM7XWEaeIHGrNMzB/view?usp=drivesdk",
    "https://drive.google.com/file/d/1a-nY11YKeFro5Vu69nzvmdFG_YdLQysH/view?usp=drivesdk",
    "https://drive.google.com/file/d/1FAloAkLYPjehGYHGIAOEIdW1iqocyAIU/view?usp=drivesdk",
    "https://drive.google.com/file/d/13XKSfc725PHNgsYRzFq-sbdtlKpFPjp7/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OPSoVdSSbnj1TOk5t0h-wRTMX87vIbBm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1xM1XGFZtx7PW9CkNm_qkXp70S4_AY6vp/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QGEYocHOM49R2R8vS3JfDXO6OVBzQnfk/view?usp=drivesdk",
    "https://drive.google.com/file/d/1yAOrHNUTrmPvfh80okDb1-m9UNlqU6GK/view?usp=drivesdk",
    "https://drive.google.com/file/d/12L440nTpqBcIK8-PTZ6h3CwdHmYGeRnI/view?usp=drivesdk",
    "https://drive.google.com/file/d/17BE3v0uTlakRv7N6l_SrIrJpFO-SEz00/view?usp=drivesdk",
    "https://drive.google.com/file/d/1o3gGW6ROhiRF9yC22P2ont6w6Xt3hBiJ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1o5iHVfWl9_wZqb8kaQcwu1S-5exGf0S-/view?usp=drivesdk",
    "https://drive.google.com/file/d/1RTv9_u4XbIjFLGtw9zPGeaXVLiOj6be8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1rYTwGG8MuQ-xeSK-pgsLchhbj85TVIiw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1QtZJork5B0h5ue4LELdvK60NKbLeowxw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1q982j766fcKvMw96hhfTDLRDl8UL_0A_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1PXNEj79MZgA5n6-4vwPED4od-e0MZlzN/view?usp=drivesdk",
    "https://drive.google.com/file/d/15zlxNVtyD1Of3Y62t65f_eRkd_80GsWQ/view?usp=drivesdk",
    "https://drive.google.com/file/d/1OWl5DeKFKSBClDyO0OPAuMI4pUr0W_Kj/view?usp=drivesdk",
    "https://drive.google.com/file/d/111g2A74LheSuxgRypTBWKIRAlmtwq6Cm/view?usp=drivesdk",
    "https://drive.google.com/file/d/1Ztr5rHtHO18ZHZe3l3obFuws5eJ7fkfv/view?usp=drivesdk",
    "https://drive.google.com/file/d/1BrCOPjKAsPCPYRARQZsruyMS14Y1tCZT/view?usp=drivesdk",
    "https://drive.google.com/file/d/12z49RV6GuJUiGSkIDYyNCfYEv7hq9bmV/view?usp=drivesdk",
    "https://drive.google.com/file/d/1wvj6ynitV7ZoZWNFEKqZZGzFuRtq1CL6/view?usp=drivesdk",
    "https://drive.google.com/file/d/1zih3MF0siAP3wYIrxX-FqM75Kr7HfFH_/view?usp=drivesdk",
    "https://drive.google.com/file/d/1DHfRLz1SqtAKkQxNWeiM8_L8OpxAT4aF/view?usp=drivesdk",
    "https://drive.google.com/file/d/1LEZCWWQutPcIC49yOrXlNfYb_SwvsLR8/view?usp=drivesdk",
    "https://drive.google.com/file/d/1ZY0OGkRizbglwSVRI6DYfhfCL3cX5Olj/view?usp=drivesdk",
    "https://drive.google.com/file/d/19z16hwb8NjxHWKjmSi2B4vFXmKhsl8VH/view?usp=drivesdk",
    "https://drive.google.com/file/d/15K_PRpiDY5ZH-SKm5NunCifHofKa7d75/view?usp=drivesdk",
    "https://drive.google.com/file/d/1EQWIVUD2_tpSOy9-EEtMn5lPgaXrOWIw/view?usp=drivesdk",
    "https://drive.google.com/file/d/1A0dC6ILTgRjGMZGGwyJVux8oa1-W-5et/view?usp=drivesdk",
];

const year2017Pics = [
    "https://drive.google.com/file/d/1AVEyHd2BkDPr2FRBQOuJ_PHhFJtIlhKD/view?usp=drive_link",
    "https://drive.google.com/file/d/13q_bIPSHePYKqiorW2WYqwtenX8Tea3d/view?usp=drive_link",
    "https://drive.google.com/file/d/1lMgopQYbj1o1ECEatZA3unV9MQZUMFYo/view?usp=drive_link",
    "https://drive.google.com/file/d/1Cpo3wM1RoCFEBAsDfnl9eY_SNHcw9SLh/view?usp=drive_link",
    "https://drive.google.com/file/d/1Gg0NDrVuBXoETUrJQyng_8bJjccn7rV8/view?usp=drive_link",
    "https://drive.google.com/file/d/1DMPehNeKezcVuMbyDMkswJmK8cUeLRXu/view?usp=drive_link",
    "https://drive.google.com/file/d/1UbKqLMS7wcjrJdHgEaMSptYar8xkRpsj/view?usp=drive_link",
    "https://drive.google.com/file/d/1f8PbTgjAE7i6LxEaM9J4jZP4GBjhhgbX/view?usp=drive_link",
    "https://drive.google.com/file/d/1vtr6bNMbeAx94WFmUfWZnxD6n29IZgWp/view?usp=drive_link",
    "https://drive.google.com/file/d/1dwaaqiGUk-Zm_nVJ6HItrKPuj1O3YoWs/view?usp=drive_link",
    "https://drive.google.com/file/d/1u3a9diA-SrB-zzIxUA2qH7x69PrWpNYd/view?usp=drive_link",
    "https://drive.google.com/file/d/1ggF7Q_tjotTzvFysGeZVWH1-j2o2LiK4/view?usp=drive_link",
];

const yearbeforeusButton = document.querySelector('#yearbeforeus');
const year2015Button = document.querySelector('#year2015');
const year2016Button = document.querySelector('#year2016');
const year2017Button = document.querySelector('#year2017');
const year2018Button = document.querySelector('#year2018');
const year2019Button = document.querySelector('#year2019');
const year2020Button = document.querySelector('#year2020');
const year2021Button = document.querySelector('#year2021');
const year2022Button = document.querySelector('#year2022');
const year2023Button = document.querySelector('#year2023');
const year2024Button = document.querySelector('#year2024');
const year2025Button = document.querySelector('#year2025');
const yearhomeButton = document.querySelector('#yearhome');
const photosButton = document.querySelector('#photosbutton');
const yearListContainer = document.querySelector('#yearlistcontainer');
const allYearButtons = document.querySelectorAll('#yearlistcontainer button');
const photosContainer = document.querySelector('#photoscontainer');
const backgroundPic = document.querySelector('#backgroundpic');
const backbackgroundPic = document.querySelector('#backbackgroundpic');
const bodyOfDocument = document.querySelector('body');


const showAllYearButtons = () => {
    yearListContainer.classList.remove('hide');
    photosButton.classList.add('hide');
};

const hideYearsShowPhotosButton = () => {
    photosButton.classList.remove('hide');
    yearListContainer.classList.add('hide');
    photosContainer.innerHTML = '';
    photosButton.style.opacity = '0';
    photosButton.style.animation = 'fadeIn 1s ease-in-out forwards';
};

yearhomeButton.addEventListener('click', hideYearsShowPhotosButton);
photosButton.addEventListener('click', showAllYearButtons);
photosButton.addEventListener('click', () => { photosContainer.innerHTML = '' });
photosButton.addEventListener('click', () => setBackgroundURL("img/church1.jpg"));

const setBackgroundURL = (imageLink) => {
    const body = document.querySelector('body');
    body.style.backgroundImage = '';
    backgroundPic.src = imageLink;
    backbackgroundPic.src = imageLink;
    backgroundPic.classList.remove('backgroundpic');
    backgroundPic.classList.remove('backgroundimage');
    backgroundPic.classList.add('backgroundpic');
};

const getFinalImageLinks = (initialLinks) => {
    const tempImageLinks = [];
    const linkInsideNumbers = initialLinks.map(str => str.slice(32, 65));
    for (let i = 0; i < initialLinks.length; i++) {
        tempImageLinks.push(`https://drive.google.com/thumbnail?id=${linkInsideNumbers[i]}&sz=s4000`)
    };
    return tempImageLinks;
};

const insertPicsToContainer = (initialLinks) => {
    const finalImageLinks = getFinalImageLinks(initialLinks);
    for (let i = 0; i < initialLinks.length; i++) {
        const picAndNumberContainer = document.createElement('div');
        const picNumber = document.createElement('p');
        picNumber.textContent = `${i + 1}`;
        picNumber.classList.add('picnumber');
        const imagePic = document.createElement('img');
        imagePic.src = finalImageLinks[i];
        picAndNumberContainer.appendChild(picNumber);
        picAndNumberContainer.appendChild(imagePic);
        imagePic.style.animationDelay = `${i * 0.5}s`;
        picNumber.style.animationDelay = `${i * 0.5}s`;
        photosContainer.appendChild(picAndNumberContainer);
    }
};

const yearButtonFunction = (buttonSelect, picsLinks, bgimage) => {
    buttonSelect.addEventListener('click', () => {
        photosContainer.innerHTML = '';
        insertPicsToContainer(picsLinks);
        setBackgroundURL(bgimage);
    });
};

yearButtonFunction(yearbeforeusButton, beforeusPics, "img/beforeus.png");
yearButtonFunction(year2015Button, year2015Pics, "img/2015.png");
yearButtonFunction(year2016Button, year2016Pics, "img/2016.png");
yearButtonFunction(year2017Button, year2017Pics, "img/2017.png");
yearButtonFunction(year2018Button, year2018Pics, "img/2018.png");
yearButtonFunction(year2019Button, year2019Pics, "img/2019.png");
yearButtonFunction(year2020Button, year2020Pics, "img/2020.png");
yearButtonFunction(year2021Button, year2021Pics, "img/church3.jpg");
yearButtonFunction(year2022Button, year2022Pics, "img/church3.jpg");
yearButtonFunction(year2023Button, year2023Pics, "img/church3.jpg");
yearButtonFunction(year2024Button, year2024Pics, "img/church3.jpg");
yearButtonFunction(year2025Button, year2025Pics, "img/church3.jpg");

